os: osx
osx_image: xcode8.2
language: objective-c
sudo: false

env:
  global:
    - THEOS=~/theos
    - SDKVERSION=10.1
    - SYSROOT=~/theos/sdks/iPhoneOS10.1.sdk

before_install:
  - HOMEBREW_NO_AUTO_UPDATE=1 brew install dpkg ldid

  - git clone --recursive git://github.com/theos/theos.git ~/theos
  - rm -rf ~/theos/sdks
  - git clone --recursive git://github.com/theos/sdks.git ~/theos/sdks

script:
  - cd Redstone
  - make package
